### ISSUE TITLE
It's been 8 months since the last publish to NPM

### ISSUE THREAD

**Issue by felgeekpe** [ddsky/unibox#10]
Hey

it's been  more than 8 months since unibox was last published to NPM, last available version is 1.15.0.

Can we have an update on this please?

**Comment by felgeekpe** [comment]
you need to do **npm publish**, further reading:
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by ddsky** [comment]
Thank you, I just published again. Anyway you can pull releases from the repo instead of me pushing?
