### ISSUE TITLE
.error() deprecated since jquery 3

### ISSUE THREAD

**Issue by ThomasTr** [ddsky/unibox#6]
Hi, having trouble since the last update to jquery 3 (jquery latest in your bower.json)
The .error() function is deprecated since 1.8 and removed in 3: https://api.jquery.com/error/
unibox.js row 393

**Comment by ddsky** [comment]
Thanks Thomas, I'll look into it right away.

**Comment by ThomasTr** [comment]
Thanks for your quick anwser

just replace 

jQuery("img").error(function () {

with         

jQuery("img").on( "error", function () {

**Comment by ddsky** [comment]
yup, just did that, tag 1.15.11, thanks for noticing.
