### ISSUE TITLE
missing words highlight

### ISSUE THREAD

**Issue by ctimoteo** [ddsky/unibox#7]
Hello,
sorry to bother with some support request...
I am trying unibox,
i had no problems with suggests, creating the "sections", adding links and images,
great work!

but i am struggling with word highlight list,

i am sending from backend for example:
{
    "words": [
        {
            "name": "clothing",
        }
     ],
     "suggests": {...}
}

when i get suggestions for "clo" for example, i expected to see in top of results the following,

**clo**thing

but i don't see nothing, only suggests sections, as expected.

i already inspected the DOM, i think that i don't have the highlight section hidden, i also tried to add an div with content <div id="unibox-invisible"> etc, without any success,

i missed anything on documentation?

could you provide some examples how to get the highlight feature working?

i am also preparing a pull request with some extra configurations and another html to append  that i needed to add, and i think that may be useful to share with you and other users

Thanks in advance,

Best regards

**Comment by ddsky** [comment]
Hi,

That is not how the "words" highlighting is supposed to work. The documentation is not clear on this I'm sorry. What you want works like this:

suggestUrl should point to an endpoint that returns a "clothing" suggest when you type "clo". In the config the "highlight" parameter should be set to true.

The sampleSite.html contains the setup.
